baseURL = "localhost:1313"
languageCode = "pt-BR"
defaultContentLanguage = "ptbr"

title = "Hugo Learn Documentation"
theme = "hugo-theme-learn"
themesdir = "../.."
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/raffaeldutra/docker.raffaeldutra.github.io"
  description = "Documentação Docker"
  author = "Rafael Dutra"
  showVisitedLinks = true
  themeVariant = "green"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.ptbr]
title = "Documentação Docker"
weight = 1
languageName = "Português"

[[Languages.ptbr.menu.shortcuts]]
name = "<i class='fa fa-fw fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/raffaeldutra/docker.raffaeldutra.github.iolearn"
weight = 10

[[Languages.ptbr.menu.shortcuts]]
name = "<i class='fa fa-fw fa-bookmark'></i> Hugo Documentation"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20
